import js from '@eslint/js';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    // Generated by ts-rs from cosmos-common; regenerate rather than edit.
    ignores: ['dist', 'src/generated', 'src-tauri/target'],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],
      // `_`-prefixed bindings are the idiom used to drop keys when
      // destructuring a record in the stores.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // Empty catch blocks are deliberate throughout: localStorage access,
      // malformed SSE frames and clipboard writes must never break a render.
      'no-empty': ['error', { allowEmptyCatch: true }],
    },
  },
  {
    // Vendored shadcn primitives, listed last so these win. They're
    // regenerated by the shadcn CLI, so rewriting them to satisfy the React
    // Compiler rules would be undone by the next `shadcn add`.
    files: ['src/components/ui/**'],
    rules: {
      'react-hooks/purity': 'off',
      'react-hooks/set-state-in-effect': 'off',
      'react-hooks/refs': 'off',
      'react-refresh/only-export-components': 'off',
    },
  },
);
