#!/usr/bin/env node
/**
 * Builds the Cosmos mark from the two Inkscape sources, which differ only in
 * their gradient colours:
 *
 *   src/assets/icon_simple.svg       light ink, for dark backgrounds
 *   src/assets/icon_simple_dark.svg  dark ink, for light backgrounds
 *        |
 *        +-> public/favicon.svg      self-contained, follows the OS scheme
 *        +-> src/assets/icon-mark.svg  stops read --mark-* and follow the app theme
 *
 * Run after editing either source:  node scripts/build-mark.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const appDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => readFileSync(path.join(appDir, p), 'utf8');

/** The single path and its radial gradient, ignoring Inkscape's own metadata. */
function parse(file) {
  const svg = read(file);
  const d = /<path\b[^>]*?\sd="([^"]*)"/s.exec(svg)?.[1];
  const radial = /<radialGradient\b([^>]*)>/s.exec(svg)?.[1];
  const stops = [...svg.matchAll(/stop-color:\s*([^;"]+)/g)].map((m) => m[1].trim());
  if (!d || !radial || stops.length !== 2) throw new Error(`${file}: unexpected structure`);

  const geometry = ['cx', 'cy', 'fx', 'fy', 'r', 'gradientTransform', 'gradientUnits']
    .map((key) => [key, new RegExp(`\\s${key}="([^"]*)"`).exec(radial)?.[1]])
    .filter(([, value]) => value !== undefined)
    .map(([key, value]) => `${key}="${value}"`)
    .join(' ');

  return { d: d.split(/\s+/).join(' '), geometry, stops };
}

const light = parse('src/assets/icon_simple.svg'); // light ink
const dark = parse('src/assets/icon_simple_dark.svg'); // dark ink
if (light.d !== dark.d) throw new Error('the two sources no longer share one path');

writeFileSync(
  path.join(appDir, 'public/favicon.svg'),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16">
  <!-- Generated by scripts/build-mark.mjs. Follows the OS colour scheme, which
       is what the browser chrome around a tab uses. -->
  <defs>
    <radialGradient id="ink" ${light.geometry}>
      <stop class="a" offset="0"/>
      <stop class="b" offset="1"/>
    </radialGradient>
  </defs>
  <style>
    .a { stop-color: ${dark.stops[0]} }
    .b { stop-color: ${dark.stops[1]} }
    @media (prefers-color-scheme: dark) {
      .a { stop-color: ${light.stops[0]} }
      .b { stop-color: ${light.stops[1]} }
    }
  </style>
  <path fill="url(#ink)" d="${light.d}"/>
</svg>
`,
);

// No <style> here: an inline SVG's stylesheet applies to the whole document.
// The stops read theme tokens instead, so the mark follows the app's theme.
writeFileSync(
  path.join(appDir, 'src/assets/icon-mark.svg'),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16">
  <!-- Generated by scripts/build-mark.mjs. Colours come from --mark-0/--mark-1
       in App.css; the fallbacks match the dark theme. -->
  <defs>
    <radialGradient id="cosmos-mark-ink" ${light.geometry}>
      <stop offset="0" style="stop-color:var(--mark-0, ${light.stops[0]})"/>
      <stop offset="1" style="stop-color:var(--mark-1, ${light.stops[1]})"/>
    </radialGradient>
  </defs>
  <path fill="url(#cosmos-mark-ink)" d="${light.d}"/>
</svg>
`,
);

console.log('wrote public/favicon.svg and src/assets/icon-mark.svg');
